title: IT Gateway
description: IT theory, practical skills, and exam preparation for Grade 8-12
theme: just-the-docs

# Enable search
search_enabled: true

# Enable navigation structure
nav_external_links:
  - title: Google Classroom
    url: https://classroom.google.com
    hide_icon: false

# Enable copy code buttons
enable_copy_code_button: true

# Footer content
footer_content: "Created by MrCooks &copy; 2026"
